version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: campuscloud
      POSTGRES_USER: campuscloud
      POSTGRES_PASSWORD: campuscloud
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: rostinm/campuscloud:latest
    depends_on:
      - db
      - logstash
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-soft-darkness-a4q2zq2r-pooler.us-east-1.aws.neon.tech:5432/CAMPUSCLOUD?sslmode=require
      SPRING_DATASOURCE_USERNAME: CAMPUSCLOUD_owner
      SPRING_DATASOURCE_PASSWORD: npg_Xa4r0iETympv
    ports:
      - "8080:8080"

volumes:
  esdata: