apiVersion: apps/v1
kind: Deployment
metadata:
  name: campuscloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campuscloud
  template:
    metadata:
      labels:
        app: campuscloud
    spec:
      containers:
        - name: campuscloud
          image: rostinm/campuscloud:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: ""
            - name: SPRING_DATASOURCE_USERNAME
              value: ""
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: RECAPTCHA_SECRET
              value: ""
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
